name: Bug report
description: Create a report to help us improve
title: "[Bug report]"
labels: ["bug"]
projects: ["SCER"]
assignees: 
  - atg-abhishek
  - Henry-WattTime
  - navveenb
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Outline bug
      description: Outline Outline bug Details
      placeholder: Tell us what you see
      value: "Add details" 
    validations:
      required: true
  - type: dropdown
    id: WG
    attributes:
      label: Issue dependency with other TF Groups
      multiple: true
      options:
        - No Dependency
        - Policy WG
        - Community WG
        - OS WG
