---
name: Consistency and IPR Review (Add project title)
description: Enter the Issue title.
title: '[Consistency & IPR Review]: '
labels: [Consistency & IPR Review]
projects: ["Add project"]
assignees:
- Add Project lead details
body:
  - type: textarea
    id: project-review
    attributes:
      label: Consistency and IPR Review
      description: Consistency and IPR Review
      placeholder: Consistency and IPR Review
      value: "1. Add a link to project Proposal\n\n2. Review Start Date:\n\n3. Review Closing Date:\n\n4. All comments will be submitted on this issue and indicate if you agree or object to this project.**"
    validations:
      required: true
  - type: dropdown
    id: action-item
    attributes:
      label: Approve Project
      multiple: true
      options:
        - Approve
        - Object
        - Abstain

