name:  Documentation
description: Issue associated with Documentation
title: "[Documentation]"
labels: ["documentation"]
projects: ["sci"]
assignees: 
  - atg-abhishek
  - Henry-WattTime
  - navveenb
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Outline Action Item Details
      description: Outline Action Item Details
      placeholder: Tell us what you see
      value: "Add details"
    validations:
      required: true
  - type: dropdown
    id: TF-Groups
    attributes:
      label: Issue dependency with other TF Groups
      multiple: true
      options:
        - No Dependency
        - Policy WG
        - Community WG
        - OS WG
