name:  Project Proposal Approval
description: Project Proposal Approval
title: "[Project-Approval]"
labels: ["Project-Approval"]
projects: ["sci"]
assignees: 
  - Henry-WattTime
  - navveenb

body:
  - type: textarea
    id: project-review
    attributes:
      label: Project Review Comments
      description: Details
      placeholder: What needs to be done
      value: "1. Add a link to project Proposal\n\n2. Review Start Date:\n\n3. Review Closing Date:\n\n4. All comments will be submitted into this issue and indicate if you Agree or Object to this project."
    validations:
      required: true
  - type: dropdown
    id: action-item
    attributes:
      label: Approve Project
      multiple: true
      options:
        - Approve
        - Object
        - Abstain
 
